Repository ideditor/schema-builder, pull requests merged in 2023-05, with the labels that each got.

#97 fix id-tagging-schema broken on windows
  lib/build.js
Labels: bug

#99 Fix typo in iconCrossReferences in readme
  README.md
Labels: documentation

#98 allow to specify alternative keys for some field types
  README.md
  schemas/field.json
Labels: enhancement
